producers:

- name:   JD Maresco
  email:  jdm@generalassemb.ly

instructors:

- name:   Peter Lai
  email:  peter.lai@generalassemb.ly
- name:   Greg MacWilliam
  email:  greg.macwilliam@generalassemb.ly
- name:   Travis Vander Hoop
  email:  travis@generalassemb.ly

locations:

- name:     General Assembly @ 1776
  address:  1133 15th St NW, 8th Floor, Washington, DC 20005
  hours:    8:30am to 5:30pm
- name:     1776 DC
  address:  1133 15th St NW, 12th Floor, Washington, DC 20005
  hours:    5:30pm to 10:00pm

office_hours:

- tuesdays:   6pm to 8pm
  instructor: Greg
- wednesdays: 6pm to 8pm
  instructor: Peter
- thursdays:  6pm to 8pm
  instructor: Travis

homework_lead: vanderhoop
